MVC_Ticari_Otomasyon/Models/siniflar/Departman.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MVC_Ticari_Otomasyon.Models.siniflar
{
    public class Departman
    {
        [Key]
        public int departmanID { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string departmanAd { get; set; }
        public bool Durum { get; set; } 

        public ICollection<Personel> Personels { get; set; }
    }
}

MVC_Ticari_Otomasyon/Controllers/DepartmanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC_Ticari_Otomasyon.Models.siniflar;

namespace MVC_Ticari_Otomasyon.Controllers
{
    public class DepartmanController : Controller
    {
        // GET: Departman
        Context c=new Context();
        public ActionResult Index()
        {
            var degerler=c.Departmans.Where(x=>x.Durum==true).ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult DepartmanEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DepartmanEkle(Departman d)
        {
            c.Departmans.Add(d);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DepartmanSil(int id)
        {
            var dep = c.Departmans.Find(id);
            dep.Durum = false;
            c.SaveChanges();
            return RedirectToAction("Index");

        }
        public ActionResult DepartmanGetir(int id)
        {
            var dpt = c.Departmans.Find(id);
            return View("DepartmanGetir",dpt);
        }
        public ActionResult DepartmanGuncelle(Departman d)
        {
            var dept = c.Departmans.Find(d.departmanID);
            dept.departmanAd = d.departmanAd;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DepartmanDetay(int id)
        {
            var degerler=c.personels.Where(x=>x.Departmanid==id).ToList();
            var dpt=c.Departmans.Where(x=>x.departmanID==id).Select(y=>y.departmanAd).FirstOrDefault();
            ViewBag.d = dpt;
            return View(degerler);
        }
        public ActionResult DepartmanSatisPersonel(int id)
        {
            var degerler = c.SatisHareketleris.Where(x => x.Personelid == id).ToList();
            var per = c.personels.Where(x => x.personelID == id).Select(y => y.personelAd +" " + y.personelSoyad).FirstOrDefault();
            ViewBag.dpers=per;
            return View(degerler);
        }
    }
}

MVC_Ticari_Otomasyon/Views/Departman/DepartmanDetay.cshtml
@using MVC_Ticari_Otomasyon.Models.siniflar
@model List<Personel>
@{
    ViewBag.Title = "DepartmanDetay";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Departman Detay Sayfası</h2>
<br />

<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Departman Adı: @ViewBag.d</li>
</ol>
<table class="table table-hover">
    <tr>
        <th>Personel ID</th>
        <th>AD</th>
        <th>SOYAD</th>
        <th>GÖRSEL</th>
        <th>SATIŞLAR</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.personelID</td>
            <td>@x.personelAd</td>
            <td>@x.personelSoyad</td>
            <td>@x.personelGorsel</td>
            <td><a href="/Departman/DepartmanSatisPersonel/@x.personelID" class="btn btn-default" style="background-color:orange">Satışlar</a></td>
        </tr>
    }


</table>

MVC_Ticari_Otomasyon/Views/Departman/DepartmanEkle.cshtml
@model MVC_Ticari_Otomasyon.Models.siniflar.Departman
@{
    ViewBag.Title = "DepartmanEkle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Yeni Departman Sayfası</h2>
<br />
<form class="form-group" method="post">
    @Html.LabelFor(x => x.departmanAd)
    @Html.TextBoxFor(x => x.departmanAd, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Kaydet</button>
</form>

<div class="form-group" method="post">
    <label>Kategori No:</label>
    @Html.DisplayFor(model => model.departmanID)
</div>
<div class="form-group">
    <label>Kategori Ad:</label>
    @Html.DisplayFor(model => model.departmanAd)
</div>

MVC_Ticari_Otomasyon/Views/Departman/DepartmanGetir.cshtml
@model MVC_Ticari_Otomasyon.Models.siniflar.Departman
@{
    ViewBag.Title = "DepartmanGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Departman Güncelleme</h2>
<br />
@using (Html.BeginForm("DepartmanGuncelle", "Departman", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(x => x.departmanAd)
        @Html.TextBoxFor(x => x.departmanAd, new { @class = "form-control" })
        @Html.HiddenFor(x => x.departmanID)
    </div>
    <br />
    <button class="btn btn-default" style="background-color:lawngreen">Güncelle</button>
}

MVC_Ticari_Otomasyon/Views/Departman/DepartmanSatisPersonel.cshtml
@using MVC_Ticari_Otomasyon.Models.siniflar
@model List<SatisHareketleri>
@{
    ViewBag.Title = "DepartmanSatisPersonel";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Departman Personel Satış</h2>
<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Personel Adı: @ViewBag.dpers</li>
</ol>
<table class="table table-condensed">
    <tr>
        <th>SATIŞ ID</th>
        <th>ÜRÜN</th>
        <th>MÜŞTERİ</th>
        <th>FİYAT</th>
        <th>ADET</th>
        <th>TOPLAM</th>
        <th>TARİH</th>
        <th>YAZDIR</th>
    </tr>
    @foreach (var x in Model)
            {
                <tr>
                    <td>@x.satisID</td>
                    <td>@x.Urunler.urunAd</td>
                    <td>@x.Müsteriler.müsteriAd @x.Müsteriler.müsteriSoyad</td>
                    <td>@x.fiyat</td>
                    <td>@x.adet</td>
                    <td>@x.toplamTutar</td>
                    <td>@x.tarih</td>
                    <td><a href="#" class="btn btn-default"style="background-color:dodgerblue">Yazdır</a></td>
                </tr>
            }
</table>

MVC_Ticari_Otomasyon/Views/Departman/Index.cshtml
@using MVC_Ticari_Otomasyon.Models.siniflar;
@model List<Departman>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<table class="table table-bordered" style="margin-top:20px"
    <tr>
        <th>ID</th>
        <th>Departman Adı</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Detaylar</th>
    </tr>


    @foreach (var dep in Model)
    {
                <tr>
                    <td>@dep.departmanID</td>
        <td>@dep.departmanAd</td>
        <td><a href="/Departman/DepartmanSil/@dep.departmanID"class="btn btn-danger">Sil</a></td>
        <td><a href="/Departman/DepartmanGetir/@dep.departmanID"class="btn btn-success">Departman Güncelle</a></td>
        <td><a href="/Departman/DepartmanDetay/@dep.departmanID" class="btn btn-success" style="background-color:gold">Detaylar</a></td>
                </tr>


     }

</table>
<a href="/Departman/DepartmanEkle" class="btn btn-info">Departman Ekle</a>